### PR TITLE
  fix: Prevent automatic probation from unsuspending fraud accounts

### LINKED ISSUE #2049: Admin/Risk - suspended account was unsuspended by probationary measure?
I could be wrong here, but it looks like for UID 24838599 was suspended for fraud (by me)
Two sales were then charged back, which made the balance negative
The account then was automatically put on probation, because of the negative balance. 

It seems like this allowed the creator to login and change their bank account details. Not sure why they'd do that, but they seem to be scammy individuals overall so I'm sure it was for no good reason. 

Ideally, once an account is suspended for fraud, it stays that way

### PR DESCRIPTION
**Pull request by romitg2**
fixes #2049 

### Problem:
- Admin suspends user for fraud → user_risk_state = 'suspended_for_fraud'
- Chargebacks occur → balance drops below -$100
- LowBalanceFraudCheckWorker triggers automatic probation
- System transitions: suspended_for_fraud → on_probation 
- Fraudster can now login and change payment details

**This should not happen if user is already suspended, then user should stay suspended**

### Root Cause:
- The low balance fraud check system (app/models/concerns/user/low_balance_fraud_check.rb) automatically probates users with negative balances without checking if they're already suspended (more restrictive state)

### Solution:
```rb
    # Don't unsuspend users with automated probation
    disable_refunds_and_put_on_probation! unless recently_probated_for_low_balance? || suspended?
```

### Tests Result: (local run)
Screenshot 2025-12-10 at 8 30 08 AM

### AI Disclosure:
- used claude-sonnet-4.5 to understand codebase

### Live Stream Disclosure:
- watched all 4 live streams

### CODE REVIEW

File: app/models/concerns/user/low_balance_fraud_check.rb [hunk 1]
```diff
@@ -26,7 +26,8 @@ def check_for_low_balance_and_probate(refunded_or_disputed_purchase_id)
     return if unpaid_balance_cents > LOW_BALANCE_THRESHOLD
 
     AdminMailer.low_balance_notify(id, refunded_or_disputed_purchase_id).deliver_later
-    disable_refunds_and_put_on_probation! unless recently_probated_for_low_balance?
+
+    disable_refunds_and_put_on_probation! unless recently_probated_for_low_balance? || suspended?
```
Comment (romitg2) [inline app/models/concerns/user/low_balance_fraud_check.rb:30]: Suspended users cannot login, so putting user on probation would restore login access for user (this should not happen)
- so, don't put user on probation, if already suspended.
