### PR TITLE
fix(ui): inconsistent button styles in Embed media modal

### LINKED ISSUE #2082: Fix Embed Media modal to display consistent styling
The Embed Media modal currently shows inconsistent UI between the “Embed link” and “Upload” buttons

Image

### PR DESCRIPTION
**Pull request by 4arjun**
Fix #2082 
## Summary
The “Embed media” modal displays misaligned action buttons — the Upload button overlaps its border, and the Embed link button uses a different UI style. The UI has been updated to match both buttons and ensure a consistent design. Previously, these differences resulted in uneven spacing and broke the visual balance of the button group.

## Before

Screenshot 2025-11-19 at 4 28 32 PM 

##

## After

Screenshot 2025-11-19 at 4 15 50 PM

##

## Mobile
| Before | After |
|--------|--------|
|  |  |

| Before | After |
|--------|--------|
|  |  |

## AI Usage
No AI was used to generate any of this code.

## Confirmation
I have watched the Gumroad PR reviews live streaming video.

## Self-Review
I have self-reviewed all the code that I have written.

### CODE REVIEW

File: app/javascript/components/ProductEdit/ContentTab/index.tsx [hunk 1]
```diff
@@ -592,14 +592,19 @@ const ContentTabContent = ({ selectedVariantId }: { selectedVariantId: string |
 
                 <Modal open={showEmbedModal} onClose={() => setShowEmbedModal(false)} title="Embed media">
                   <p>Paste a video link or upload images or videos.</p>
-                  <Tabs>
-                    <Tab isSelected aria-controls={`${uid}-embed-tab`}>
-                      <Icon name="link" />
-                      <h4>Embed link</h4>
+                  <Tabs variant="buttons">
```
Comment (4arjun) [inline app/javascript/components/ProductEdit/ContentTab/index.tsx:595]: Switched the embed/upload controls to the shared Tabs “buttons” variant so both actions look identical

**Comment by Madeersani** [comment]
https://github.com/antiwork/gumroad/pull/2078

**Comment by 4arjun** [comment]
@binary-koan Could you review?

File: app/javascript/components/ProductEdit/ContentTab/index.tsx [hunk 2]
```diff
@@ -592,14 +592,19 @@ const ContentTabContent = ({ selectedVariantId }: { selectedVariantId: string |
...
+                    <Tab isSelected aria-controls={`${uid}-embed-tab`} asChild>
+                      <button type="button">
+                        <Icon name="link" />
+                        <div>
```
Comment (binary-koan) [inline app/javascript/components/ProductEdit/ContentTab/index.tsx]: Is there a reason for this `div`? Seems to work without it for me

Comment (4arjun) [reply app/javascript/components/ProductEdit/ContentTab/index.tsx]: Oh, that div wasn't intentional, it was just leftover from an earlier layout attempt. I have removed it.
Thanks for the review!

**Review by binary-koan — APPROVED** [review]
Looks good, thanks! I'm assuming the failing tests are flaky, will merge
