### PR TITLE
fix: disable signup with stripe

### LINKED ISSUE #2450: Disable signup with Stripe
### What
- Add a feature flag to enable or disable signup via Stripe.
- Existing users should be able to log in via Stripe, but ensure it won't create new accounts and connect Stripe automatically

### PR DESCRIPTION
**Pull request by stefanbinoj**
Fixes #2450 

## Summary 
- Added a new flag `disable_stripe_signup` (defaults to false, meaning Stripe signup is ALLOWED by default)
- To block Stripe signups, activate the flag: `Feature.activate(:disable_stripe_signup)`
- Checks if user account present if yes logs in else shows alert toast with 
`Signing up with Stripe is currently disabled. Please sign up with email first, then connect your Stripe account.`

### ScreenShots `/signup` page: 
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>

Screenshot 2025-12-24 at 1 13 50 PM

</td>
<td>

Screenshot 2025-12-24 at 1 14 53 PM

</td>
</tr>
</table>

### Feature page: 

Screenshot 2025-12-24 at 2 01 10 PM

### Tests: 

Screenshot 2025-12-24 at 10 31 12 AM

 ---

Screenshot 2025-12-24 at 10 29 52 AM

---

Screenshot 2025-12-24 at 10 30 22 AM

> Failing tests are unrelated due to missing env
### AI disclosure
Used Claude Opus 4.5 via Opencode for initial drafting 

### Confirmation
I have watched all Antiwork Livestreams

### CODE REVIEW

File: app/javascript/components/Authentication/SocialAuth.tsx [hunk 1]
```diff
@@ -2,9 +2,15 @@ import * as React from "react";
...
+import { useFeatureFlags } from "$app/components/FeatureFlags";
 
 export const SocialAuth = () => {
-  const next = new URL(useOriginalLocation()).searchParams.get("next");
+  const originalLocation = useOriginalLocation();
+  const featureFlags = useFeatureFlags();
+
+  const next = new URL(originalLocation).searchParams.get("next");
+  const isSignupPage = new URL(originalLocation).pathname === "/signup";
+  const showStripe = isSignupPage ? !featureFlags.disable_stripe_signup : true;
```
Comment (stefanbinoj) [inline app/javascript/components/Authentication/SocialAuth.tsx:13]: Stripe auth button is **hidden** when : 
- page is /signup
- feature flag is true

File: app/controllers/user/omniauth_callbacks_controller.rb [hunk 2]
```diff
@@ -92,7 +92,18 @@ def stripe_connect
...
     if logged_in_user.blank?
-      user = User.find_or_create_for_stripe_connect_account(auth)
+      existing_merchant_account = MerchantAccount.where(charge_processor_merchant_id: auth.uid).alive
+                                    .find { |ma| ma.is_a_stripe_connect_account? }
+      existing_user = existing_merchant_account&.user
+
+      if existing_user.present?
+        user = existing_user
+      elsif Feature.active?(:disable_stripe_signup)
+        flash[:alert] = "Signing up with Stripe is currently disabled. Please sign up with email first, then connect your Stripe account."
```
Comment (stefanbinoj) [inline app/controllers/user/omniauth_callbacks_controller.rb]: If it's a signup returns this flash

File: app/controllers/user/omniauth_callbacks_controller.rb [hunk 3]
```diff
@@ -92,7 +92,18 @@ def stripe_connect
     end
 
     if logged_in_user.blank?
-      user = User.find_or_create_for_stripe_connect_account(auth)
+      existing_merchant_account = MerchantAccount.where(charge_processor_merchant_id: auth.uid).alive
+                                    .find { |ma| ma.is_a_stripe_connect_account? }
+      existing_user = existing_merchant_account&.user
```
Comment (stefanbinoj) [inline app/controllers/user/omniauth_callbacks_controller.rb]: 1. First checks for existing user in `MerchantAccount` table. 
2. If yes finds the first one that is a Stripe Connect account via `is_a_stripe_connect_account?` method

File: app/controllers/user/omniauth_callbacks_controller.rb (hunk 2 above)
Comment (hchhabra) [reply app/controllers/user/omniauth_callbacks_controller.rb]: This will return an error even if there's an existing user account that matches the email of the Stripe account I think? It should login in that case. Also, connecting a Stripe account is no longer supported either.

**Comment by stefanbinoj** [comment]
@hchhabra _a thanks for the comment, addressed the comment and fixed tests accordingly. Can you take a look and trigger CI if everything seems fine?

File: app/controllers/user/omniauth_callbacks_controller.rb [hunk 4]
```diff
@@ -92,7 +92,25 @@ def stripe_connect
...
+
+        if user.nil?
+          if Feature.active?(:disable_stripe_signup)
+            flash[:alert] = "Signing up with Stripe is currently disabled. Please sign up with email first."
+            return safe_redirect_to referer
+          else
+            user = User.find_or_create_for_stripe_connect_account(auth)
+          end
+        end
+      end
```
Comment (stefanbinoj) [inline app/controllers/user/omniauth_callbacks_controller.rb:110]: 1. If not found, check for existing user by email from Stripe auth data 
2. If still no user found AND disable_stripe_signup is active → show error
3. Otherwise, create new user via find_or_create_for_stripe_connect_account

File: app/javascript/inertia/app_wrapper.tsx [hunk 5]
```diff
@@ -43,7 +45,9 @@ export default function AppWrapper({ children, global }: { children: React.React
             locale: global.locale,
           }}
         >
-          <SSRLocationProvider value={global.href}>{children}</SSRLocationProvider>
+          <FeatureFlagsProvider value={global.feature_flags}>
+            <SSRLocationProvider value={global.href}>{children}</SSRLocationProvider>
+          </FeatureFlagsProvider>
```
Comment (stefanbinoj) [inline app/javascript/inertia/app_wrapper.tsx:50]: Previously we used to rely on `app/javascript/utils/serverComponentUtil.tsx` for `useFeatureFlag` in `SocialAuthButton.tsx`. But since we migrated /login and /signup to inertia pages  in #2410 thus we moved provider to here also so that inertia page also has access

**Comment by stefanbinoj** [comment]
@hchhabra _a all failing tests seems unrelated

File: app/controllers/user/omniauth_callbacks_controller.rb [hunk 6]
```diff
@@ -92,7 +92,25 @@ def stripe_connect
...
 
     if logged_in_user.blank?
-      user = User.find_or_create_for_stripe_connect_account(auth)
+      existing_merchant_account = MerchantAccount.where(charge_processor_merchant_id: auth.uid).alive
+                                    .find { |ma| ma.is_a_stripe_connect_account? }
+      existing_user = existing_merchant_account&.user
+
+      if existing_user.present?
+        user = existing_user
+      else
```
Comment (hchhabra) [inline app/controllers/user/omniauth_callbacks_controller.rb]:
```suggestion
      user = MerchantAccount.where(charge_processor_merchant_id: auth.uid).alive
                            .find { |ma| ma.is_a_stripe_connect_account? }&.user

      if user.nil?
```

File: app/controllers/user/omniauth_callbacks_controller.rb [hunk 7]
```diff
@@ -92,7 +92,25 @@ def stripe_connect
...
+        stripe_email = auth.dig("info", "email")
+        user = User.find_by(email: stripe_email) if stripe_email.present?
+
+        if user.nil?
+          if Feature.active?(:disable_stripe_signup)
+            flash[:alert] = "Signing up with Stripe is currently disabled. Please sign up with email first."
```
Comment (hchhabra) [inline app/controllers/user/omniauth_callbacks_controller.rb]:
```suggestion
            flash[:alert] = "Sorry, we could not find an account associated with that Stripe account."
```

Since this error message will be shown when trying to login (and not signup), this makes more sense imo.

File: spec/controllers/user/omniauth_callbacks_controller_spec.rb [hunk 8]
```diff
@@ -151,6 +150,50 @@ def safe_redirect_path(path, allow_subdomain_host: true)
...
+        Feature.activate(:disable_stripe_signup)
+        request.env["omniauth.params"] = { "referer" => signup_path }
+      end
+
+      after { Feature.deactivate(:disable_stripe_signup) }
+
+      it "does not allow new users to sign up via Stripe" do
+        expect { post :stripe_connect }.not_to change { User.count }
+
+        expect(flash[:alert]).to eq "Signing up with Stripe is currently disabled. Please sign up with email first."
```
Comment (hchhabra) [inline spec/controllers/user/omniauth_callbacks_controller_spec.rb]:
```suggestion
        expect(flash[:alert]).to eq "Sorry, we could not find an account associated with that Stripe account."
```

**Comment by stefanbinoj** [comment]
@hchhabra thanks for helping out i really appreciate it. Thank you 🙏🏻 
All tests seems to be passing!

**Review by hchhabra — APPROVED** [review]
Thanks, @stefanbinoj !
