### PR TITLE
Fix:  Unpublished products remain enabled when unchecking "Show unpublished and ineligible products" on Collaborator Form

### LINKED ISSUE #2813: Bug: Unpublished products remain enabled when unchecking "Show unpublished and ineligible products" on Collaborator Form
## What

While creating or editing a collaboration, unchecking "Show unpublished and ineligible products" does not exclude unpublished products from being processed, making them part of the collaboration when saved.

### Expected Behavior
Unchecking "Show unpublished and ineligible products" should disable all unpublished products that were previously enabled, regardless of whether "All products" is checked or not. These products should not be included in the submission when the checkbox is unchecked.

> [!NOTE]
> This bug was found during migration of #2565 and reproduced on main branch commit 4011562a95572fcf3ddf009ba001bcd68a13c4b5 (which is the commit prior to merge of #2565)
> We're handling it as a separate issue from the migration as recommended by @EmCousin in https://github.com/antiwork/gumroad/pull/2565#discussion_r2668393013

### Case 1 - With "All Products" Checked

1. Navigate to https://gumroad.com/collaborators/ and select a collaboration record to edit
2. Enable "All products" if disabled
3. Check "Show unpublished and ineligible products" box (this should enable unpublished product)
4. Uncheck "Show unpublished and ineligible products" box (this hides the unpublished product but does not disable it)
5. Submit the form and check the collaboration record (Unpublished product is part of collaboration)

https://github.com/user-attachments/assets/6f90e556-c5dc-4f47-bc10-364b0970e68f

### Case 2 - With "All Products" Unchecked

1. Navigate to https://gumroad.com/collaborators/ and select a collaboration record to edit
2. Disable "All products" if enabled
3. Check "Show unpublished and ineligible products" box and enable any unpublished product for collaboration
4. Uncheck "Show unpublished and ineligible products" box (this hides the unpublished product but does not disable it)
5. Submit the form and check the collaboration record (Unpublished product is part of collaboration)

https://github.com/user-attachments/assets/c637d293-d8b7-4704-a043-80f413beedc3

----

## Specs Verifying The Bug

Image

<details>

<summary>
<h2>Snippet Of Specs</h2>
</summary>

Image

</details>

### PR DESCRIPTION
**Pull request by sm17p**
Closes #2813 

## Root Cause

The logic on `L359` & `L361` works in sync to only update the `enabled `status for unpublished products when `apply_to_all_products` is `true` AND `enabled` is `true`, skipping the disabled flow completely for both cases from the issue.

```tsx
onChange={(evt) => {
  const enabled = evt.target.checked;
  setShowUnpublishedOrIneligibleProducts(enabled);
  if (form.data.apply_to_all_products) { //  L359
    form.data.products.forEach((item, index) => {
      if (!item.has_another_collaborator && enabled && !item.published) { // L361
        form.setData(`products.${index}.enabled`, enabled);
      }
    });
  }
}}
/>
Show unpublished and ineligible products
```

## Solution
When "Show unpublished and ineligible products" is unchecked, the updated logic now handles both enable/disable flows by:

1. Removing the `if (form.data.apply_to_all_products)` condition so the logic runs regardless of the "All products" checkbox state
2. Removing the `&& enabled` check from the condition, allowing it to process both checked and unchecked states
3. Setting the `enabled` state to `enabled && form.data.apply_to_all_products`, which properly disables unpublished products when either checkbox is unchecked

### Before

https://github.com/user-attachments/assets/c3824ff8-4c61-48c6-98bf-f883434ef39d

### After

https://github.com/user-attachments/assets/9fcb0f64-40a3-47f3-9a1a-8b6d6501d2e9

### Before

https://github.com/user-attachments/assets/e358a534-7a0f-4c06-b362-6f0805245cf5

### After

https://github.com/user-attachments/assets/9f677081-2c3f-4c0b-a1f7-fe9f9d46a678

## Test Results

specs passing

---

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/antiwork/gumroad/blob/main/CONTRIBUTING.md)
- [x] I have watched [Gumroad PR review livestreams](https://www.youtube.com/@anti-work)
- [x] I have performed a self-review and left review comments on my PR
- [x] I have added/updated tests for my changes

---

## AI Disclosure
I've used Cursor auto mode to generate specs for this task

### CODE REVIEW

File: app/javascript/components/Collaborators/Form.tsx [hunk 1]
```diff
@@ -356,13 +356,11 @@ const CollaboratorForm = ({
...
-                if (form.data.apply_to_all_products) {
-                  form.data.products.forEach((item, index) => {
-                    if (!item.has_another_collaborator && enabled && !item.published) {
-                      form.setData(`products.${index}.enabled`, enabled);
-                    }
-                  });
-                }
+                form.data.products.forEach((item, index) => {
+                  if (!item.has_another_collaborator && !item.published) {
+                    form.setData(`products.${index}.enabled`, enabled && form.data.apply_to_all_products);
```
Comment (sm17p) [inline app/javascript/components/Collaborators/Form.tsx:361]: ## Case 1 - With "All Products" Checked

### When checked
1. enabled = true, apply_to_all_products = true
2. Evaluates to `true && true = true` and enables unpublished products

### When unchecked
1. enabled = false, apply_to_all_products = true
2. Evaluates to `false && true = false` and disables unpublished products


## Case 2 - With "All Products" Unchecked

### When checked
1. enabled = true, apply_to_all_products = false
2. Evaluates to `true && false = false` and does not enable unpublished products

### When disabled
1. enabled = false, apply_to_all_products = false
2. Evaluates to `false&& false = false` and disables unpublished products if it was enabled

File: spec/requests/collaborators_spec.rb [hunk 2]
```diff
@@ -406,6 +406,65 @@
...
+
+          expect(page).to have_alert(text: "Changes saved!")
+          expect(page).to have_current_path(collaborators_path)
+
+          collaborator = seller.collaborators.last
+          expect(collaborator.products).to eq [product1, product2, product3]
+          expect(collaborator.products).not_to include(product4, product5)
+        end.to change { seller.collaborators.count }.from(1).to(2)
+           .and change { ProductAffiliate.count }.from(2).to(5)
+      end
```
Comment (sm17p) [inline spec/requests/collaborators_spec.rb:435]: I can merge this spec with existing one but have kept it separate for clarity. 

LMK if any adjustments are needed

**Review by sm17p — COMMENTED** [review]
@EmCousin Please have a look this is ready for review 🙏

**Review by nyomanjyotisa — APPROVED** [review]
Look good to me, thank you
