### PR TITLE
Fix: Purchase search fails when URL parameters with empty values are present

### LINKED ISSUE #2175: Admin: Purchase search fails when multiple URL parameters are present
When searching for purchases by email using the Search Purchases field in admin, no results are returned even though there are valid purchases for that email.

This appears to be caused by additional URL parameters interfering with the search. For example:

* **Does not work:**
  `https://gumroad.com/admin/search/purchases?query=email%40example.com&user_query=&purchase_query=email%40example.com&affiliate_query=&product_title_query=&purchase_status=&card_type=&transaction_date=&last_4=&expiry_date=&price=`

* **Works:**
  `https://gumroad.com/admin/search/purchases?query=email%40example.com`

Image

### PR DESCRIPTION
**Pull request by romitg2**
fixes #2175 

## Problem: 
When searching for purchases by email using the Search Purchases field in admin, no results are returned even though there are valid purchases for that email.

Does not work:
```
https://gumroad.com/admin/search/purchases?query=email%40example.com&user_query=&purchase_query=email%40example.com&affiliate_query=&product_title_query=&purchase_status=&card_type=&transaction_date=&last_4=&expiry_date=&price=
```
Works:
```
https://gumroad.com/admin/search/purchases?query=email%40example.com
```

## Before: 
https://github.com/user-attachments/assets/b9f41511-f7f5-48e1-bdaa-73bf0406a481

## After:
https://github.com/user-attachments/assets/6ef7a7bc-3f17-409a-8683-841a5f9d0725

## Root Cause:

Ruby's .any? method returns `true` for empty strings, causing the code to incorrectly filter out empty string parameters when the frontend sent empty string parameters.

## Solution: 
 Changed `.any?` to `.any?(&:present?)`, 
- .present? correctly identifies empty strings, nil, and whitespace-only strings as "not present"

## Test Result: Before Fix
Screenshot 2025-12-13 at 1 38 48 PM

## Test Result: After Fix
Screenshot 2025-12-13 at 1 39 41 PM

### AI Disclosure:
- no AI used

### Live stream Disclosure:
- watched all live streams

### CODE REVIEW

File: app/services/admin_search_service.rb [hunk 1]
```diff
@@ -58,7 +58,7 @@ def search_purchases(query: nil, product_title_query: nil, purchase_status: nil,
       purchases = purchases.where(id: license.purchase_id)
     end
 
-    if [transaction_date, last_4, card_type, price, expiry_date].any?
+    if [transaction_date, last_4, card_type, price, expiry_date].any?(&:present?)
```
Comment (romitg2) [inline app/services/admin_search_service.rb:61]: Ruby's .any? method returns true for empty strings.

---
Changed .any? to .any?(&:present?),
- .present? correctly identifies empty strings, nil, and whitespace-only strings as "not present"

File: spec/services/admin_search_service_spec.rb [hunk 2]
```diff
@@ -20,6 +20,22 @@
       expect(purchases).to include(purchase_1, purchase_2, purchase_3)
     end
 
+    it "returns purchases when searching by email with empty card parameters" do
```
Comment (romitg2) [inline spec/services/admin_search_service_spec.rb:23]: Image
