### PR TITLE
fix: Add missing color variables to profile preview on settings page

### LINKED ISSUE #2648: Profile Preview shows incorrect background colors
Some elements in the Profile Preview on the settings page do not apply the user-selected background color. Instead, they fall back to the default app colors, resulting in an inconsistent and incorrect preview.

Image

### PR DESCRIPTION
**Pull request by SalmanNajah**
Fix #2648

# Description
Some elements in the Profile Preview on the settings page do not use the user’s selected background color. Instead, they fall back to the default app colors, causing the preview to appear partially incorrect.

## Problem
The user’s color preferences were applied, but Tailwind was reading different color variables. Because those variables weren’t set inside the preview wrapper, Tailwind fell back to the default body colors.

https://github.com/antiwork/gumroad/blob/baa379b2d8535e1dec3bfe087f4c34c49271b44a/app/javascript/pages/Settings/Profile/Show.tsx#L251-L267

## Solution
Updated the Profile Preview styles to include the missing Tailwind color variables, ensuring all elements use the correct background color.

---

# Before

https://github.com/user-attachments/assets/e50e0f7c-908d-4411-b61c-fc54fceb10e3

# After

https://github.com/user-attachments/assets/3e6478e9-2f2d-4b6c-9ad1-786c72821621

---

# Checklist

- [x] I have read the [contributing guidelines](https://github.com/antiwork/gumroad/blob/main/CONTRIBUTING.md)
- [x] I have watched [Gumroad PR review livestreams](https://www.youtube.com/@anti-work)
- [x] I have performed a self-review and left review comments on my PR
- [x] I have added/updated tests for my changes -- No breaking changes (Just a CSS change)

---

# AI Disclosure

Used GPT-5.1-codex via VS Code for refactoring.

### CODE REVIEW

File: app/javascript/pages/Settings/Profile/Show.tsx [hunk 1]
```diff
@@ -261,6 +261,16 @@ export default function SettingsPage() {
               "--body-bg": "rgb(var(--filled))",
               "--contrast-primary": "var(--filled)",
               "--contrast-filled": "var(--color)",
+              "--color-body": "var(--body-bg)",
```
Comment (SalmanNajah) [inline app/javascript/pages/Settings/Profile/Show.tsx:263]: Added the required Tailwind color variables here to ensure all Preview elements use the correct colors.

File: app/javascript/types/css.d.ts [hunk 2]
```diff
@@ -10,5 +10,15 @@ declare module "react" {
     "--primary"?: string;
     "--body-bg"?: string;
     "--contrast-primary"?: string;
+    "--color-body"?: string;
```
Comment (SalmanNajah) [inline app/javascript/types/css.d.ts:13]: Updated its types.
