### PR TITLE
fix(tests): Fix three flaky system tests

### LINKED ISSUE #2462: Fix flakey tests
We need to fix all three flakey tests in this build - https://github.com/antiwork/gumroad/actions/runs/20488922819

### PR DESCRIPTION
**Pull request by sahilagar**
## Summary

Fixes #2462

Fixes three flaky system tests by addressing root causes rather than adding timing workarounds.

### Audio player progress assertions (`rich_text_editor_spec.rb`)

The tests asserted on transient `00:00` → `00:01` timing which is inherently racy. Fixed by:
- Checking for `[aria-label="Pause"]` first to confirm audio is playing
- Using explicit `00:01` → `00:02` timing assertions to verify progress advanced

### Shipping offer codes (`shipping_offer_codes_spec.rb`)

The offer code was being applied twice: once via URL, then again via the `check_out` helper filling in the discount field. Fixed by:
- Removing the duplicate `offer_code` parameter since it's already applied via URL query params
- Adding assertion to verify the offer code was applied via URL before checkout

### Payments IBAN field (`payments_spec.rb`)

The test filled in the IBAN field before React finished rendering the form. Added `expect(page).to have_field("IBAN")` to wait for the form to be ready.

## Testing

image

Ran each modified test 3+ times locally with 0 failures. The shipping test requires CI for subdomain DNS resolution.

## AI Disclosure

This PR was developed with AI assistance (Claude) for analyzing flaky test patterns and improving the fix approach.

### CODE REVIEW

**Comment by binary-koan** [comment]
Could you link to CI runs where these flaked so it's easier to understand the reasoning?

**Comment by binary-koan** [comment]
Sorry, I see the CI run is linked in the issue

File: spec/requests/products/edit/rich_text_editor_spec.rb [hunk 1]
```diff
@@ -544,9 +544,8 @@
 
         # Allow playing the file
         click_on "Play"
-        expect(page).to have_selector("[aria-label='Progress']", text: "00:00")
-        expect(page).to have_selector("[aria-label='Progress']", text: "00:01")
         expect(page).to have_selector("[aria-label='Pause']")
+        expect(page).to have_selector("[aria-label='Progress']", text: /00:0[1-9]/)
```
Comment (binary-koan) [inline spec/requests/products/edit/rich_text_editor_spec.rb]: Same comment as https://github.com/antiwork/gumroad/pull/2516 applies, does it work to test 00:01 -> 00:02 if 00:00 is too short?

File: spec/requests/purchases/product/shipping/shipping_offer_codes_spec.rb [hunk 2]
```diff
@@ -33,7 +33,7 @@
 
     visit "/l/#{@product.unique_permalink}/#{@offer_code.code}"
     add_to_cart(@product, offer_code: @offer_code)
-    check_out(@product, offer_code: @offer_code.code, should_verify_address: true) do
+    check_out(@product, should_verify_address: true) do
```
Comment (binary-koan) [inline spec/requests/purchases/product/shipping/shipping_offer_codes_spec.rb:38]: Nice find! Can we add just the `expect(page).to have_selector("[aria-label='Discount code']", text: offer_code)` from `check_out` here to double check the code in the URL worked?

File: spec/requests/products/edit/rich_text_editor_spec.rb (hunk 1 above)
Comment (sahilagar) [reply spec/requests/products/edit/rich_text_editor_spec.rb]: Done! Changed to explicit 00:01 -> 00:02 assertions.

File: spec/requests/purchases/product/shipping/shipping_offer_codes_spec.rb (hunk 2 above)
Comment (sahilagar) [reply spec/requests/purchases/product/shipping/shipping_offer_codes_spec.rb:38]: Good idea! Added the assertion to both shipping tests that use URL-based offer codes.

**Review by binary-koan — APPROVED** [review]
Looks great! (will go ahead and merge, hopefully these updated specs weren't in the CI batch that failed to start!)
