### PR TITLE
Fix rendering of boolean custom fields in admin

### LINKED ISSUE #2088: Purchase Receipt not loading when custom field value is boolean "true"
Currently, the purchase receipt on admin and the purchase receipt itself do not load when custom field value is boolean "true". Sharing a screenshot of the console log.

Image

### PR DESCRIPTION
**Pull request by MayaRainer**
Fixes #2088.

Currently, boolean custom fields cause a type error on the admin purchase show page.
This PR fixes that and adds a spec for it.

### CODE REVIEW

File: app/javascript/components/Admin/Purchases/index.tsx [hunk 1]
```diff
@@ -375,10 +375,10 @@ const Info = ({ purchase }: { purchase: Purchase }) => (
       ) : null}
 
       {purchase.custom_fields.map((field) => (
-        <>
+        <React.Fragment key={field.name}>
```
Comment (MayaRainer) [inline app/javascript/components/Admin/Purchases/index.tsx]: Fixes a runtime warning about not having a `key` in a list.

Comment (binary-koan) [reply app/javascript/components/Admin/Purchases/index.tsx]: Can you have multiple fields with the same name? (IIRC you can)

Might be better just to use index as these won’t change, or we could send `external_id` from the server
