### PR TITLE
Fix Missing Export Alert in Sales Data Export

### LINKED ISSUE #649: When exporting sales data no alert is shown that export is in progress
### What

When I want to export sales data, I choose the range and then click on "download". In the past, an alert would show at the top saying that the download would be emailed. Now this alert does not show.

### PR DESCRIPTION
**Pull request by AJ0070**
Fixes #649 - The alert message indicating that the export has started was not being shown when users exported sales data.

### Problem

- The export functionality was using a `NavigationButton` with an `href`, which didn't properly handle the backend's response.
- The alert message would only appear when the export was processed asynchronously (when no tempfile was generated).
- This led to inconsistent user experience, as users wouldn't receive confirmation when their export started.

### Solution

- Replaced the `NavigationButton` with a proper `<form>` element that uses the `POST` method.
- Added an `onSubmit` handler that:
  - Shows the alert message immediately when the form is submitted.
  - Handles both synchronous and asynchronous export flows.
  - Maintains all existing functionality while providing better user feedback.

## Summary by CodeRabbit

* **New Features**
  * Added an in‑UI notice in the Customers export popover: when exporting more than 2,000 rows, users are informed that the export will be processed in the background and emailed to them.
  * The export action and parameters remain unchanged; this is a presentational enhancement to clarify large-export behavior.

### CODE REVIEW

**Comment by AJ0070** [comment]
@slavingia, could I get a review on this?

**Comment by slavingia** [comment]
Could you showcase the before/after to show it worked? Also, full test suite run.

**Comment by AJ0070** [comment]
@slavingia can you run the test on CI on this?(Saw your message on telegram). I'll upload videos as soon as I get back to my laptop.

**Comment by AJ0070** [comment]
### After:

https://github.com/user-attachments/assets/0681632e-9f11-466d-9e05-8645a9efb1b2

**Comment by AJ0070** [comment]
I’m not able to provide a “before” video because the issue occurred intermittently and only under specific backend response conditions (when a tempfile was generated immediately), which I can’t reproduce at the moment.

The attached “after” video shows the fix working as intended — the export trigger now uses a POST form with an `onSubmit` handler that immediately displays the alert, ensuring consistent feedback regardless of whether the export is processed synchronously or asynchronously. This change removes the dependency on unpredictable backend timing and ensures that users always see confirmation when their export starts.

**Comment by slavingia** [comment]
Test suite passing?

**Comment by AJ0070** [comment]
I realized this approach would require changes to the backend implementation for the flash warning, which I don’t think is ideal. Instead, I can display an inline message like: "Exports over 2,000 rows will be processed in the background and emailed to you." This is a simpler solution and won’t require any backend logic changes.

**Comment by AJ0070** [comment]
### After Change: 
WhatsApp Image 2025-08-11 at 21 53 48_edf5c501

WhatsApp Image 2025-08-11 at 21 55 41_fdf90d4f

**Comment by AJ0070** [comment]
@slavingia Any suggestions on this?

**Comment by slavingia** [comment]
Seems janky and I liked the first approach better. We shouldn't show this if someone only has 1 sale for example

**Comment by AJ0070** [comment]
> Seems janky and I liked the first approach better. We shouldn't show this if someone only has 1 sale for example

 
@slavingia This is only showed when sale record is more than 2000 but if you want to proceed with the first approach I'll complete that implementation and will open a new PR soon.

File: app/javascript/components/server-components/Audience/CustomersPage.tsx [hunk 1]
```diff
@@ -417,6 +417,11 @@ const CustomersPage = ({
               >
                 Download
               </NavigationButton>
+              {count > 2000 && (
+                <div style={{ marginTop: "0.5rem", color: "#666" }}>
```
Comment (slavingia) [inline app/javascript/components/server-components/Audience/CustomersPage.tsx]: can we use tailwind?

**Comment by AJ0070** [comment]
@slavingia changed it to tailwind

**Comment by slavingia** [comment]
and screenshot + e2e test update?

**Comment by AJ0070** [comment]
### Using consistent tailwind:

image


image
