### PR TITLE
Fix missing font and color variables in product and bundle edit previews

### LINKED ISSUE #3457: Missing font and color variables in product and bundle edit previews
The product edit and bundle edit previews do not reflect the user’s preferred background color and font selected in Settings. As a result, the preview UI appears inconsistent with the actual product appearance.

### PR DESCRIPTION
**Pull request by SalmanNajah**
Fixes #3457

# Description
The product edit and bundle edit previews do not reflect the user’s preferred background color and font selected in Settings. As a result, the preview UI appears inconsistent with the actual product appearance.

## Problem
On the product edit and bundle edit pages, the preview falls back to the default body color and font instead of using the user’s configured profile settings, resulting in a misleading preview.

## Solution
Update the product and bundle edit previews to use the user’s profile background color and font, ensuring the previews match the configured settings.

---

# Demo (Product edit and Bundle edit)
| Before| After|
|-|-|
| image| image
|image | image
|image | image
| image| image

### Before

https://github.com/user-attachments/assets/827e8364-0f99-413a-bdad-5f7e4cc02577

### After

https://github.com/user-attachments/assets/0b2bbcae-eeac-4a3c-b795-8fb1b47dd550

---

# Test Results
image

---

# Checklist

- [x] I have read the [contributing guidelines](https://github.com/antiwork/gumroad/blob/main/CONTRIBUTING.md)
- [x] I have watched [Gumroad PR review livestreams](https://www.youtube.com/@anti-work)
- [x] I have performed a self-review and left review comments on my PR
- [x] I have added/updated tests for my changes

---

# AI Disclosure

Used Claude-sonnet-4.5 via VS Code for understanding the data flow and for the implementation. Self-reviewed by me.

### CODE REVIEW

File: app/javascript/components/BundleEdit/Layout.tsx [hunk 1]
```diff
@@ -40,6 +44,7 @@ export const Layout = ({
   isLoading?: boolean;
 }) => {
   const { bundle, updateBundle, id, uniquePermalink } = useBundleEditContext();
+  const currentSeller = useCurrentSeller();
```
Comment (SalmanNajah) [inline app/javascript/components/BundleEdit/Layout.tsx:76]: Using seller data from the global react context via `useCurrentSeller()`

File: app/javascript/components/BundleEdit/Layout.tsx [hunk 2]
```diff
@@ -93,6 +98,20 @@ export const Layout = ({
...
   const navigate = useNavigate();
 
+  const profileColors = currentSeller
+    ? {
+        "--accent": hexToRgb(currentSeller.profileHighlightColor),
+        "--contrast-accent": hexToRgb(getContrastColor(currentSeller.profileHighlightColor)),
+        "--filled": hexToRgb(currentSeller.profileBackgroundColor),
+        "--color": hexToRgb(getContrastColor(currentSeller.profileBackgroundColor)),
+      }
+    : {};
```
Comment (SalmanNajah) [inline app/javascript/components/BundleEdit/Layout.tsx:102]: Update the preview background color based on the current seller's color preference

File: app/javascript/components/BundleEdit/Layout.tsx [hunk 3]
```diff
@@ -93,6 +98,20 @@ export const Layout = ({
...
+
+  const fontUrl =
+    currentSeller?.profileFont && currentSeller.profileFont !== "ABC Favorit"
+      ? `https://fonts.googleapis.com/css2?family=${encodeURIComponent(currentSeller.profileFont)}:wght@400;600&display=swap`
+      : null;
+
```
Comment (SalmanNajah) [inline app/javascript/components/BundleEdit/Layout.tsx:108]: Get the font info based on the current seller's font preference

File: app/javascript/components/BundleEdit/Layout.tsx [hunk 4]
```diff
@@ -202,9 +221,34 @@ export const Layout = ({
               scaleFactor={0.4}
               style={{
                 border: "var(--border)",
+                borderRadius: "var(--border-radius-2)",
```
Comment (SalmanNajah) [inline app/javascript/components/BundleEdit/Layout.tsx:214]: Added missing tailwind variables and outer border-radius.

File: app/javascript/components/BundleEdit/Layout.tsx [hunk 5]
```diff
@@ -202,9 +221,34 @@ export const Layout = ({
...
+                "--color-accent-foreground": "rgb(var(--contrast-accent))",
+                "--color-primary": "rgb(var(--primary))",
+                "--color-primary-foreground": "rgb(var(--contrast-primary))",
+                "--color-active-bg": "rgb(var(--color) / var(--gray-1))",
+                "--color-muted": "rgb(var(--color) / var(--gray-3))",
                 backgroundColor: "rgb(var(--filled))",
+                color: "rgb(var(--color))",
               }}
             >
+              {fontUrl ? (
```
Comment (SalmanNajah) [inline app/javascript/components/BundleEdit/Layout.tsx:235]: To load the fonts in the preview

File: app/javascript/components/CurrentSeller.ts [hunk 6]
```diff
@@ -42,6 +48,9 @@ export const parseCurrentSeller = (data: unknown): CurrentSeller | null => {
     timeZone: parsed.time_zone,
     has_published_products: parsed.has_published_products,
     isNameInvalidForEmailDelivery: parsed.is_name_invalid_for_email_delivery,
+    profileBackgroundColor: parsed.profile_background_color,
+    profileHighlightColor: parsed.profile_highlight_color,
+    profileFont: parsed.profile_font,
```
Comment (SalmanNajah) [inline app/javascript/components/CurrentSeller.ts:53]: Parse new variables from snake_case to camelCase.

File: app/javascript/components/ProductEdit/Layout.tsx
Comment (SalmanNajah) [inline app/javascript/components/ProductEdit/Layout.tsx:1]: Same changes as in `app/javascript/components/BundleEdit/Layout.tsx`

File: app/javascript/types/css.d.ts [hunk 7]
```diff
@@ -10,5 +10,15 @@ declare module "react" {
...
+    "--color-body"?: string;
+    "--color-background"?: string;
+    "--color-foreground"?: string;
+    "--color-border"?: string;
+    "--color-accent"?: string;
+    "--color-accent-foreground"?: string;
+    "--color-primary"?: string;
+    "--color-primary-foreground"?: string;
+    "--color-active-bg"?: string;
+    "--color-muted"?: string;
```
Comment (SalmanNajah) [inline app/javascript/types/css.d.ts:22]: Added appropriate types for the custom Tailwind variables

File: app/presenters/user_presenter.rb [hunk 8]
```diff
@@ -43,6 +43,9 @@ def as_current_seller
       time_zone: { name: time_zone.tzinfo.name, offset: time_zone.tzinfo.utc_offset },
       has_published_products: user.products.alive.exists?,
       is_name_invalid_for_email_delivery: user.is_name_invalid_for_email_delivery?,
+      profile_background_color: user.seller_profile.background_color,
+      profile_highlight_color: user.seller_profile.highlight_color,
+      profile_font: user.seller_profile.font,
```
Comment (SalmanNajah) [inline app/presenters/user_presenter.rb:48]: Updated the User presenter to expose `profile_background_color`, `profile_highlight_color`, and `profile_font` to the frontend.

File: app/javascript/components/BundleEdit/Layout.tsx [hunk 9]
```diff
@@ -15,6 +17,9 @@ import { Tabs, Tab } from "$app/components/ui/Tabs";
 import { useIsAboveBreakpoint } from "$app/components/useIsAboveBreakpoint";
 import { WithTooltip } from "$app/components/WithTooltip";
 
+const hexToRgb = (hex: string) =>
+  `${parseInt(hex.slice(1, 3), 16)} ${parseInt(hex.slice(3, 5), 16)} ${parseInt(hex.slice(5), 16)}`;
```
Comment (nyomanjyotisa) [inline app/javascript/components/BundleEdit/Layout.tsx]: We now have `hexToRgb` in 3 places, can we make it DRY?

File: app/presenters/user_presenter.rb (hunk 8 above)
Comment (nyomanjyotisa) [reply app/presenters/user_presenter.rb:48]: Can we include this in tests?

**Comment by SalmanNajah** [comment]
@nyomanjyotisa _a I've addressed all the comments. Please take a look.

File: spec/presenters/user_presenter_spec.rb [hunk 10]
```diff
@@ -57,6 +57,27 @@
...
+        time_zone: { name: time_zone.tzinfo.name, offset: time_zone.tzinfo.utc_offset },
+        has_published_products: seller.products.alive.exists?,
+        is_name_invalid_for_email_delivery: seller.is_name_invalid_for_email_delivery?,
+        profile_background_color: seller.seller_profile.background_color,
+        profile_highlight_color: seller.seller_profile.highlight_color,
+        profile_font: seller.seller_profile.font
+      )
+    end
+  end
+
```
Comment (SalmanNajah) [inline spec/presenters/user_presenter_spec.rb:80]: Image

**Comment by slavingia** [comment]
As the oldest PR, would be great to merge soon :)

**Review by nyomanjyotisa — APPROVED** [review]
Looks good to me, thank you @SalmanNajah
