### PR TITLE
fix: Update Library creator counts to respect the "Show archived only" filter

### LINKED ISSUE #2469: Update Library creator counts to respect the "Show archived only" filter
### What

- [ ] Update Library creator counts to respect the "Show archived only" filter

###
Creator counts are currently calculated using all purchases, regardless of whether archived items are filtered. This causes the counts to mismatch what’s actually shown in the Library. Counts should always reflect what the user sees.

Image

### PR DESCRIPTION
**Pull request by romitg2**
fixes #2469 

# Description
- Update Library creator counts to respect the "Show archived only" filter. ( earlier creator counts was not respecting "Show archived only" filter ) 

## Problem
- The Library page's creator counts were calculated in the backend using all purchases, regardless of the "Show archived only" filter. This caused the counts to mismatch what the user actually sees when filtering.

## Solution: 
- updated frontend code to update creator counts to respect the "show archived only" filter
- also, Removed the backend count calculation since the frontend already recalculates counts based on the archive filter state. The backend now only provides creator id and name.

---

# Before:
https://github.com/user-attachments/assets/5ef14847-801b-4cf6-8977-52fea0efd2f0

# After:
https://github.com/user-attachments/assets/b1e3a9ed-a7b7-45db-9d73-bcfc0e698bdf

### Test Result: (Local run)

Screenshot 2025-12-25 at 11 39 58 AM

Image
---

# Checklist

- [x] I have read the [contributing guidelines](https://github.com/antiwork/gumroad/blob/main/CONTRIBUTING.md)
- [x] I have watched [Gumroad PR review livestreams](https://www.youtube.com/@anti-work)
- [x] I have performed a self-review and left review comments on my PR
- [x] I have added/updated tests for my changes

---

# AI Disclosure

- used claude-code sonnet-4.5 to implement the tests

### CODE REVIEW

File: spec/presenters/library_presenter_spec.rb
Comment (romitg2) [inline spec/presenters/library_presenter_spec.rb:1]: - updated spec as we now do `creator_counts` calculation in forntend
Image

File: app/presenters/library_presenter.rb [hunk 1]
```diff
@@ -28,10 +28,9 @@ def library_cards
       .find_each(batch_size: 3000, order: :desc) # required to avoid full table scans. See https://github.com/gumroad/web/pull/25970
       .to_a
     creators_infos = purchases.flat_map { |purchase| purchase.link.user }.uniq.group_by(&:id).transform_values(&:first)
-    creator_counts = purchases.uniq(&:link_id).filter(&:not_is_bundle_purchase).group_by(&:seller_id).map do |seller_id, item|
-      creator = creators_infos[seller_id]
-      { id: creator.external_id, name: creator.name || creator.username || creator.external_id, count: item.size }
-    end.sort_by { |creator| creator[:count] }.reverse
+    creators = creators_infos.values.map do |creator|
+      { id: creator.external_id, name: creator.name || creator.username || creator.external_id }
+    end
```
Comment (romitg2) [inline app/presenters/library_presenter.rb:33]: - Removed count calculation
- Removed sorting by count (frontend handles this)

File: app/javascript/pages/Library/Index.tsx [hunk 2]
```diff
@@ -275,6 +275,24 @@ export default function LibraryPage() {
...
+    }, new Map<string, number>());
+
+    return creators
+      .map((creator) => ({
+        ...creator,
+        count: productCountByCreatorId.get(creator.id) ?? 0,
+      }))
+      .filter((creator) => creator.count > 0)
+      .sort((a, b) => b.count - a.count);
+  }, [creators, state.results, state.search.showArchivedOnly]);
```
Comment (romitg2) [inline app/javascript/pages/Library/Index.tsx:295]: calculates creator product counts based on the current archive filter state and It recalculates automatically whenever the archive filter toggles, ensuring counts always match the visible products.

**Comment by romitg2** [comment]
@nyomanjyotisa _a reopening after addressing your [comment](https://github.com/antiwork/gumroad/pull/2472#discussion_r2672992375) from #2472. 

Could you please Review again?

Thank you!

File: spec/requests/library_spec.rb [hunk 3]
```diff
@@ -444,6 +444,36 @@ def expect_to_show_purchases_in_order(purchases)
       expect(page).to have_selector("label:has(input[type=checkbox]):nth-of-type(4)", text: creator_with_3_products.name, visible: false)
       expect(page).to have_selector("label:has(input[type=checkbox]):nth-of-type(5)", text: creator_with_1_product.name, visible: false)
     end
+
+    it "updates creator counts when toggling archived filter" do
```
Comment (romitg2) [inline spec/requests/library_spec.rb:448]: added test to verify the fix: 

Screenshot 2025-12-25 at 11 39 58 AM

File: app/javascript/pages/Library/Index.tsx [hunk 4]
```diff
@@ -171,7 +171,7 @@ export const DeleteProductModal = ({
 
 type Props = {
   results: Result[];
-  creators: { id: string; name: string; count: number }[];
```
Comment (romitg2) [inline app/javascript/pages/Library/Index.tsx:175]: we'll calculate creators' product count client side.
