### PR TITLE
fix: broken layout on ping page

### LINKED ISSUE #2357: Layout is broken on /ping page
The layout is broken on the [ping page](https://gumroad.com/ping). It's misaligned and does not render correctly. Adjust the layout to improve visual presentation and usability.

### PR DESCRIPTION
**Pull request by romitg2**
fixes #2357 
also part of: #856 

# Before:
### desktop:
Screenshot 2025-12-20 at 11 35 35 PM
Screenshot 2025-12-16 at 11 24 38 AM

### mobile: 
Screenshot 2025-12-16 at 10 18 05 AM

https://github.com/user-attachments/assets/b7d756f9-4b61-487e-a812-0967424f06c8

# After:
### desktop:

https://github.com/user-attachments/assets/16e079c0-097d-4326-bb9d-a0e51ace8e62

https://github.com/user-attachments/assets/c1bbbd87-9421-4753-b646-2b92fd312d1f

### mobile:

https://github.com/user-attachments/assets/33c0a2b4-1d1c-49fe-9593-3ce0c508f5d9

https://github.com/user-attachments/assets/2396f9a4-f0bf-4f68-ba84-6c49d64c6fe2

## Test Result: (local run)
Screenshot 2025-12-20 at 2 24 45 PM

### AI Disclosure: 
- used claude-code sonnet 4.5 for refactoring

### live stream disclosure:
- watched all live streams

### CODE REVIEW

File: spec/controllers/public_controller_spec.rb [hunk 1]
```diff
@@ -20,6 +20,16 @@
     end
   end
 
+  describe "GET ping", inertia: true do
```
Comment (romitg2) [inline spec/controllers/public_controller_spec.rb:23]: Image

**Comment by romitg2** [comment]
@binary-koan _a could you please review again? 
- previous PR: #2359

File: app/javascript/inertia/layout.tsx [hunk 2]
```diff
@@ -28,7 +30,7 @@ export default function Layout({ children }: { children: React.ReactNode }) {
       <Head title={title} />
       <Alert initial={flash ?? null} />
       <div id="inertia-shell" className="flex h-screen flex-col lg:flex-row">
-        <Nav title="Dashboard" />
+        {loggedInUser ? <Nav title="Dashboard" /> : null}
```
Comment (romitg2) [inline app/javascript/inertia/layout.tsx:33]: for public pages (user is not logged in) we don't show navigation.

File: app/controllers/concerns/inertia_rendering.rb [hunk 3]
```diff
@@ -7,12 +7,14 @@ module InertiaRendering
...
       RenderingExtension.custom_context(view_context).merge(
-        current_user: current_user_props(current_user, impersonated_user),
         authenticity_token: form_authenticity_token,
         flash: inertia_flash_props,
         title: @title
       )
     end
+    inertia_share if: :user_signed_in? do
+      { current_user: current_user_props(current_user, impersonated_user) }
+    end
```
Comment (romitg2) [inline app/controllers/concerns/inertia_rendering.rb]: for public routes (user may not be signed in) `current_user` is not present.

Comment (binary-koan) [reply app/controllers/concerns/inertia_rendering.rb]: Can we just do this?

```ruby
current_user: user_signed_in? ? current_user_props(current_user, impersonated_user) : nil,
```

We generally prefer sending explicit nulls over omitting properties

**Comment by romitg2** [comment]
@binary-koan _a Thanks for review, addressed comment. 

could you please review again?
