### PR TITLE
 fix: payments form state validation

### LINKED ISSUE #1885: Prevent form submission when valid State is not selected
Users are currently able to submit the payment settings form without selecting a valid state. The placeholder option “State” is being treated as a valid value, which results in invalid address data on Stripe.

Gumroad:
Image

Stripe:
Image

### PR DESCRIPTION
**Pull request by tsahil01**
fixes #1885 
added requested/suggested changes from #1907
- this fix ensures users must select an actual state before submitting the form. it rejects both empty values and placeholder text, shows a clear error message, and works consistently across all supported countries.
- fixes both individual and business account type.
- The invalid api key error is of stripe.

### Before 
https://github.com/user-attachments/assets/6e398f19-640f-4d28-bffe-981cf9278924

### After (works similar for business)
https://github.com/user-attachments/assets/cdc98d66-a316-4f05-8381-16d0c73e9de4

### Use of AI
- Model: Sonnet 4.5 via Cursor
- Used for: Codebase exploration, identifying issue, tests
- All the code was manually reviewed by me

### CODE REVIEW

File: app/javascript/components/Settings/PaymentsPage/AccountDetailsSection.tsx [hunk 1]
```diff
@@ -313,10 +313,10 @@ const AccountDetailsSection = ({
                   required={complianceInfo.is_business}
                   disabled={isFormDisabled}
                   aria-invalid={errorFieldNames.has("business_state")}
-                  value={complianceInfo.business_state || "State"}
+                  value={complianceInfo.business_state || ""}
                   onChange={(evt) => updateComplianceInfo({ business_state: evt.target.value })}
                 >
-                  <option disabled>State</option>
+                  <option value="" disabled>State</option>
```
Comment (tsahil01) [inline app/javascript/components/Settings/PaymentsPage/AccountDetailsSection.tsx]: empty string and not placeholder to prevent storing placeholder as value. Applies similar to others

File: app/javascript/components/Settings/PaymentsPage/AccountDetailsSection.tsx [hunk 2]
```diff
@@ -334,10 +334,10 @@ const AccountDetailsSection = ({
                   required={complianceInfo.is_business}
                   disabled={isFormDisabled}
                   aria-invalid={errorFieldNames.has("business_state")}
-                  value={complianceInfo.business_state || "Province"}
+                  value={complianceInfo.business_state || ""}
```
Comment (tsahil01) [inline app/javascript/components/Settings/PaymentsPage/AccountDetailsSection.tsx:339]: use empty string default instead of placeholder text. applies similar to others as well

File: app/javascript/components/server-components/Settings/PaymentsPage.tsx [hunk 3]
```diff
@@ -596,8 +596,9 @@ const PaymentsPage = (props: Props) => {
     if (!complianceInfo.city) {
       markFieldInvalid("city");
     }
-    if (complianceInfo.country !== null && complianceInfo.country in props.states && !complianceInfo.state) {
+    if (complianceInfo.country !== null && complianceInfo.country.toLowerCase() in props.states && !complianceInfo.state) {
```
Comment (tsahil01) [inline app/javascript/components/server-components/Settings/PaymentsPage.tsx]: - lowercase country codes for matching  as `props.states` uses lowercase keys
- reject placeholder text `State`, `Province`, `County`. Not just empty values
- as suggested by @binary-koan, reject placeholder values if the value is now an empty string.

File: app/javascript/components/server-components/Settings/PaymentsPage.tsx [hunk 4]
```diff
@@ -667,10 +668,11 @@ const PaymentsPage = (props: Props) => {
       }
       if (
         complianceInfo.business_country !== null &&
-        complianceInfo.business_country in props.states &&
+        complianceInfo.business_country.toLowerCase() in props.states &&
```
Comment (tsahil01) [inline app/javascript/components/server-components/Settings/PaymentsPage.tsx:675]: same above validation logic for business state

File: spec/requests/settings/payments_spec.rb
Comment (tsahil01) [inline spec/requests/settings/payments_spec.rb:1]: added tests

**Review by tsahil01 — COMMENTED** [review]
added suggested changes from #1907

**Comment by tsahil01** [comment]
@binary-koan can you trigger CI for this PR?

File: spec/requests/settings/payments_spec.rb [hunk 5]
```diff
@@ -1071,6 +1071,12 @@
         select("1980", from: "Year")
         click_on("Update settings")
         expect(page).to_not have_alert(text: "Thanks! You're all set.")
+        expect(find_field("State")["aria-invalid"]).to eq "true"
+        expect(page).to have_status(text: "Please select a valid state.")
+
+        select("Rio de Janeiro", from: "State")
+        click_on("Update settings")
+        expect(page).to have_alert(text: "Thanks! You're all set.")
```
Comment (tsahil01) [inline spec/requests/settings/payments_spec.rb:1157]: now prevents saving incomplete state before updating settings.

File: spec/requests/settings/payments_spec.rb [hunk 6]
```diff
@@ -1082,6 +1088,7 @@
         fill_in("City", with: "barnabasville")
         fill_in("Phone number", with: "5022541982")
         fill_in("Postal code", with: "12345")
+        select("Rio de Janeiro", from: "State")
```
Comment (tsahil01) [inline spec/requests/settings/payments_spec.rb:1169]: added state as it is now a required filed

**Comment by tsahil01** [comment]
@binary-koan can you please review this PR? 
thanks.

**Comment by tsahil01** [comment]
@binary-koan can I add tests from #1952 in this PR, and make it more meargable? Since the changes/approach you suggested were originally copied from my old #1907 PR to all other PRs. 

added changes to tests spec in this PR

**Comment by tsahil01** [comment]
@binary-koan The CI failures might be due to multiple test suites running simultaneously and hitting Stripe's rate limit on the shared test API key. The state validation logic and tests works fine locally.

I haven't updated much code only added the suggested tests changes from another PR. 
This was yesterday - https://github.com/antiwork/gumroad/actions/runs/19282307880 (all passed expect UTM link test)
Can you try running the tests again?

**Comment by binary-koan** [comment]
> can I add tests from https://github.com/antiwork/gumroad/pull/1952 in this PR, and make it more meargable? Since the changes/approach you suggested were originally copied from my old https://github.com/antiwork/gumroad/pull/1907 PR to all other PRs.

That's fair - your original PR is what pointed me to this approach. To be clear though, this is now very much a combination of PRs so please split the bounty

Finally got a non-flaky test run, merging!

**Comment by binary-koan** [comment]
(Meant to copy the error message from https://github.com/antiwork/gumroad/pull/1951 as well before merging, doing in a separate PR)

**Comment by tsahil01** [comment]
> > can I add tests from #1952 in this PR, and make it more meargable? Since the changes/approach you suggested were originally copied from my old #1907 PR to all other PRs.
> 
> That's fair - your original PR is what pointed me to this approach. To be clear though, this is now very much a combination of PRs so please split the bounty
> 
> Finally got a non-flaky test run, merging!

Thanks for the merge. :)
Will split bounty with #1952 as I took spec from there.
