### PR TITLE
fix(nav): keep library tab active on reviews

### LINKED ISSUE #2228: Library navbar item loses active state when navigating to Reviews page
## Description
In the navbar, the Library item correctly remains highlighted when navigating to its sub-pages such as Purchases, Saved, and Following. However, when navigating to the Reviews page within Library, the Library navbar item is no longer highlighted, even though Reviews is part of the Library section.

## Expected Behavior
- The Library navbar item should remain highlighted when visiting Reviews, just like other Library sub-pages.

## Screen recording

https://github.com/user-attachments/assets/c233f6cc-9abf-40fb-9c00-d3bcbcdafcc7

### PR DESCRIPTION
**Pull request by 4arjun**
fix #2228 

## Summary
 Keep the Library nav link active while browsing Reviews by adding the Reviews URL to its match patterns
## Before

https://github.com/user-attachments/assets/e7722f36-1277-4a8b-a222-ac2a87d0da91

## After

https://github.com/user-attachments/assets/862bda4b-8e85-49a9-ba3c-850ae6500ade

## AI Usage
No AI was used to generate any of this code.

## Confirmation
I have watched the Gumroad PR reviews live streaming video.

## Self-Review
I have self-reviewed all the code that I have written.

### CODE REVIEW

File: app/javascript/components/server-components/Nav.tsx [hunk 1]
```diff
@@ -153,7 +153,7 @@ export const Nav = (props: Props) => {
             text="Library"
             icon="bookmark-heart-fill"
             href={Routes.library_url(routeParams)}
-            additionalPatterns={[Routes.wishlists_url(routeParams)]}
+            additionalPatterns={[Routes.wishlists_url(routeParams), Routes.reviews_url(routeParams)]}
```
Comment (4arjun) [inline app/javascript/components/server-components/Nav.tsx:156]: Added Routes.reviews_url(routeParams) to the Library nav link’s additionalPatterns so the Library tab stays highlighted on the Reviews page.

Comment (EmCousin) [reply app/javascript/components/server-components/Nav.tsx:156]: Can you also add this fix in `$app/components/client-components/Nav`?

**Review by EmCousin — CHANGES_REQUESTED** [review]

**Comment by 4arjun** [comment]
@EmCousin The failing tests are unrelated.

**Comment by 4arjun** [comment]
@EmCousin Could u take a look at this?

**Comment by 4arjun** [comment]
@EmCousin  Could u trigger the CI once again? The failing tests are unrelated.

**Comment by 4arjun** [comment]
@EmCousin The failing tests do not appear to be related to the changes made in this PR. I am unsure why CI continues to fail, but none of the failures seem to be connected to the modifications made here.

Screenshot 2026-01-07 at 8 13 09 PM
Screenshot 2026-01-07 at 8 13 16 PM
Screenshot 2026-01-07 at 8 13 22 PM

**Comment by 4arjun** [comment]
@EmCousin @nyomanjyotisa All tests passing.
