### PR TITLE
fix: Inconsistent scaling of empty state illustrations 

### LINKED ISSUE #1938: Inconsistent scaling of empty-state illustrations
### **Description**

Empty-state illustrations across various Gumroad pages are not scaling correctly.
Some appear too narrow and centered with large margins, while others span closer to the full container width.

There are many instances across the app. The examples below are representative cases.

**Examples:**
1. Image appears too narrow and centered with large empty margins
Image

2. Image appears closer to full-width but not completely full
Image

### **Expected behavior**
All empty-state illustrations should scale responsively to fill the full container width while maintaining 24 px padding and preserving aspect ratio.

### PR DESCRIPTION
**Pull request by TenzDelek**
Fixes #1938

# Problem
Empty state illustrations across various Gumroad pages are not scaling correctly.

### Action Performed
1. Click on any tab containing a placeholder

# Root cause analysis
Missing styling for the width

# Solution
Applying styling for the width

# Before After

### Desktop
| Before | After |
|-----------|-----------|
|image | image |

### Mobile

| Before | After |
|-----------|-----------|
| image| image|

### Desktop 
| Before | After |
|-----------|-----------|
| image| image |

### Mobile

| Before | After |
|-----------|-----------|
| image| image|

### Desktop 
| Before | After |
|-----------|-----------|
| image | image | 
image | image | 
image | image | image | image | 
image | image

### Mobile

| Before | After |
|-----------|-----------|
| image| image|

### Desktop 
| Before | After |
|-----------|-----------|
| image| image |

### Mobile 
| Before | After |
|-----------|-----------|
| image|image |

### Desktop 
| Before | After |
|-----------|-----------|
| image | image |

### Mobile 
| Before | After |
|-----------|-----------|
|image | image|

### Desktop 
| Before | After |
|-----------|-----------|
| image | image |

### Mobile
 
| Before | After |
|-----------|-----------|
| image |image |

# AI Disclosure
No AI was used for any part of this contribution.

# Confirmation
I have watched the Gumroad PR reviews live streaming video

### CODE REVIEW

File: app/javascript/pages/Library/Index.tsx [hunk 1]
```diff
@@ -352,13 +352,9 @@ export default function LibraryPage() {
       <section className="space-y-4 p-4 md:p-8">
         {state.results.length === 0 || showArchivedNotice ? (
           <Placeholder>
-            {state.results.length === 0 ? (
```
Comment (TenzDelek) [inline app/javascript/pages/Library/Index.tsx:355]: removed the redundant condition check

File: app/javascript/components/AffiliatedPage.tsx [hunk 2]
```diff
@@ -312,9 +312,7 @@ const AffiliatedPage = ({
         <section className="p-4 md:p-8">
           {initialAffiliatedProducts.length === 0 ? (
             <Placeholder>
-              <figure>
-                <img src={placeholder} />
-              </figure>
+              <PlaceholderImage alt="Become an affiliate and earn!" src={placeholder} />
```
Comment (TenzDelek) [inline app/javascript/components/AffiliatedPage.tsx]: image

I think it is best practice to provide alt text for the  tag, so we’re using the corresponding title as the alt text. any thought on this? @binary-koan

**Review by TenzDelek — COMMENTED** [review]
Self reviewed

File: app/javascript/components/AffiliatedPage.tsx (hunk 2 above)
Comment (binary-koan) [reply app/javascript/components/AffiliatedPage.tsx]: I would just set them to role=presentation as they don’t communicate anything additional to screen reader users

Comment (TenzDelek) [reply app/javascript/components/AffiliatedPage.tsx]: done with the changes. 
PTAL @binary-koan  @EmCousin

File: app/javascript/components/ui/Placeholder.tsx [hunk 3]
```diff
@@ -22,4 +22,8 @@ const Placeholder: React.FC<PlaceholderProps> = ({ className, children, ...rest
   </div>
 );
 
-export default Placeholder;
+export const PlaceholderImage = ({ alt, className, src, ...imgProps }: React.ImgHTMLAttributes<HTMLImageElement>) => (
+  <figure className="w-full">
+    <img {...imgProps} src={src} className={classNames("w-full", className)} role="presentation" />
```
Comment (binary-koan) [inline app/javascript/components/ui/Placeholder.tsx]:
```suggestion
    <img src={src} className={classNames("w-full", className)} role="presentation" {...imgProps} />
```

Better to support overriding the default behaviour (if we want an image with an `alt` for example)

File: app/javascript/components/ui/Placeholder.tsx [hunk 4]
```diff
@@ -22,4 +22,8 @@ const Placeholder: React.FC<PlaceholderProps> = ({ className, children, ...rest
   </div>
 );
 
-export default Placeholder;
```
Comment (binary-koan) [inline app/javascript/components/ui/Placeholder.tsx:25]: Nice!

**Review by binary-koan — COMMENTED** [review]
One minor comment, otherwise looks good!

**Comment by TenzDelek** [comment]
> One minor comment, otherwise looks good!

Done
