### PR TITLE
Remove inertia options from URL query params for support page

### LINKED ISSUE #2539: Bug: URL query params for support page displays inertia related options
This bug got introduced during inertia migration of support page #2317, where the URL incorrectly includes inertia visit options as query params. 

The URL should only have required query params of `id=dc629ea0c93f926709aa97cf08346c9` as per previous implementation instead of `preserveState=true&preserveScroll=true&id=dc629ea0c93f926709aa97cf08346c94`

https://github.com/user-attachments/assets/3b70d4cf-7121-4989-b091-66ac111298fc

### PR DESCRIPTION
**Pull request by sm17p**
### Closes #2539 
- #2539 

This bug got introduced during inertia migration of support page #2317, where the URL incorrectly includes inertia visit options as query params 

## Before 
- URL is `https://gumroad.dev/support?preserveState=true&preserveScroll=true&id=dc629ea0c93f926709aa97cf08346c94`

https://github.com/user-attachments/assets/3b70d4cf-7121-4989-b091-66ac111298fc

## After 
- URL is `https://gumroad.com/support?id=dc629ea0c93f926709aa97cf08346c94`
- ~~Enabled `viewTransition` to  smoothen up navigation~~

https://github.com/user-attachments/assets/9f957007-86d0-47e3-85ce-60194e0d4010

### AI Disclosure
No Usage

### Live Stream Disclosure 
Have watched all the live streams

### CODE REVIEW

**Comment by sm17p** [comment]
@binary-koan @EmCousin I believe this should be a quick fix, please have a look when you can 🙏

**Comment by sm17p** [comment]
Hi @ershad, I'm unsure what issue to tag this under. Should we create a separate issue for inertia migration related bug fixes or keep it under #856 ?

**Comment by binary-koan** [comment]
What does it look like without `viewTransition`? We don't seem to have it on other pages so maybe better to be consistent

File: app/javascript/components/support/SupportPortal.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ export default function SupportPortal() {
     const url = new URL(location.href);
     if (!isNewTicketOpen && url.searchParams.get("new_ticket")) {
       url.searchParams.delete("new_ticket");
-      router.get(url.toString(), { replace: true, preserveState: true, preserveScroll: true });
+      router.get(url.toString(), {}, { viewTransition: true });
```
Comment (EmCousin) [inline app/javascript/components/support/SupportPortal.tsx]: `replace: true, preserveState: true, preserveScroll: true` should not be removed but moved to the options object in lieu of viewTransition

File: app/javascript/components/support/SupportPortal.tsx [hunk 2]
```diff
@@ -30,7 +30,7 @@ export default function SupportPortal() {
       url.searchParams.delete("id");
     }
     if (url.toString() !== window.location.href) {
-      router.get(url.toString(), { preserveState: true, preserveScroll: true });
+      router.get(url.toString(), {}, { viewTransition: true });
```
Comment (EmCousin) [inline app/javascript/components/support/SupportPortal.tsx]: Same here

**Review by EmCousin — CHANGES_REQUESTED** [review]
Thanks for the catch @sm17p 
I personally like view transitions, but they are out of scope of this PR and I think implementing them should be part of a broader effort to ensure consistent transition effects across the app's pages: something to be discussed with the design team first.

Also, those options were there for a reason, let's keep them

**Comment by EmCousin** [comment]
Also @sm17p feel free to create a dedicated issue whenever you encounter a bug/defect like this, then you can link any PR to it :pray:

File: app/javascript/components/support/SupportPortal.tsx (hunk 1 above)
Comment (sm17p) [reply app/javascript/components/support/SupportPortal.tsx]: I think the original code before inertia migration just wanted to clear the query param on close? So maybe we don't need those other options. Can you please confirm this?

https://github.com/user-attachments/assets/666c2656-b005-46c7-8cc1-31f544657931

File: app/javascript/components/support/SupportPortal.tsx (hunk 2 above)
Comment (sm17p) [reply app/javascript/components/support/SupportPortal.tsx]: Yes added back over here

Comment (sm17p) [reply app/javascript/components/support/SupportPortal.tsx]: `router.get` is making a server request though over here. I think it should be fine with just to use client side routing? Seems to be working over here

### Demos

1. With `router.get(url.toString(), {}, { preserveState: true, preserveScroll: true })`

https://github.com/user-attachments/assets/d1f6678e-d249-40d9-bfe2-a39a2181ad93

2. `router.push({ url: url.toString(), preserveScroll: true ~~, preserveState: true~~ })`      

https://github.com/user-attachments/assets/0439b5ae-6cae-42c2-8218-fa450e258805

File: app/javascript/components/support/SupportPortal.tsx [hunk 3]
```diff
@@ -18,19 +18,20 @@ export default function SupportPortal() {
...
-      router.get(url.toString(), { replace: true, preserveState: true, preserveScroll: true });
+      router.replace({ url: url.toString() });
     }
   }, [isNewTicketOpen]);
 
   useEffect(() => {
     const url = new URL(location.href);
     if (selectedConversationSlug) {
       url.searchParams.set("id", selectedConversationSlug);
+      url.searchParams.delete("new_ticket");
```
Comment (sm17p) [inline app/javascript/components/support/SupportPortal.tsx:29]: This was needed because when a ticket is created from `support?new_ticket=true` path `location` exits with `new_ticket` param during this hook call.

`router.replace({ url: url.toString() })` from the hook above is still in a processing queue which is asynchronous. 

The previous route change call (`router.replace({ url: url.toString() })`) is thrashed or cancelled I think in the queue and hence it wouldn't delete `new_ticket` param by the time execution reaches over here

Ref - https://github.com/search?q=repo%3Ainertiajs%2Finertia%20clientVisitQueue&type=code

Image

**Comment by sm17p** [comment]
@binary-koan @EmCousin This is how it looks without view transition. I've reverted `viewTransition`, keeping `preserveScroll` enabled while selecting a conversation. Please have a look again. 

https://github.com/user-attachments/assets/32fdccbf-71a7-4af1-a1e3-5e0ccc1dbf8f

File: app/javascript/components/support/SupportPortal.tsx (hunk 1 above)
Comment (EmCousin) [reply app/javascript/components/support/SupportPortal.tsx]: That makes sense! The fix looks good. I'll run CI

**Comment by sm17p** [comment]
(just a light ping over here)

**Comment by EmCousin** [comment]
Thanks @sm17p !
