### PR TITLE
Fix popover auto-focus by removing forceMount

### LINKED ISSUE #3373: Fix: Search input not auto-focusing when popover opens
Clicking the search button in the header opens a popover but doesn't auto-focus the input field. Users have to click a second time inside the input to start typing.

Include at least one end-to-end test.

### PR DESCRIPTION
**Pull request by gianfrancopiana**
Fixes #3373
Supersedes #3872 (closed)

## What

Removed `forceMount` from the base `PopoverContent` component. With `forceMount`, Radix kept popover content permanently in the DOM (hidden via CSS), which broke its built-in focus management. `onOpenAutoFocus` only fired once on initial mount, not on subsequent opens.

Without `forceMount`, Radix mounts/unmounts content naturally on open/close, and its default behavior (focusing the first focusable element on open) works correctly for all popover consumers.

This required fixing several things that silently depended on `forceMount`:

- **Insert menu modals (X post, Button, Link, Video):** The `WithDialog` components held modal state locally inside popover content. When `PopoverClose` unmounts content, that state was destroyed before the modal could render. Removed `WithDialog` entirely and lifted modal state to `RichTextEditor`, following the existing Upsell/Review pattern. This also fulfills the TODO comments: *"remove this once popovers no longer use details"*.

- **File upload input:** The `<input type="file">` was inside `PopoverClose` in `ContentTab`. Moved it outside the popover using a ref so it persists in the DOM when the popover closes.

- **Test disclosure helper:** Radix may re-render popover content after initial mount (for positioning), and `PopoverClose` items unmount content on click. Added retry logic to `select_disclosure`/`toggle_disclosure` that distinguishes between these two cases: retries if the block hasn't executed yet (positioning re-render), rescues silently if it has (popover closed after action completed).

Cleaned up redundant focus workarounds that consumers had added: manual ref + `onOpenAutoFocus` override in `Search.tsx`, a `useEffect` focus hack in `Affiliates/Index.tsx`, and an `autoFocus` attribute in `Admin/SearchPopover.tsx`.

## Why

This was a migration artifact from PR #2742 that was never revisited. The old popover had a `useEffect` that focused `[autofocus]` elements on open. The Radix rewrite replaced that with `onOpenAutoFocus={(e) => e.preventDefault()}` but didn't provide an alternative, so no popover auto-focused unless a consumer explicitly worked around it.

Removing `forceMount` is the simplest fix. All consumers use controlled React state, so none depend on content staying mounted when closed.

## Before
CleanShot 2026-03-03 at 13 43 37

## After
CleanShot 2026-03-03 at 13 46 43

---

This PR was implemented with AI assistance using Claude Opus 4.6

### CODE REVIEW

File: spec/support/aria_extensions.rb [hunk 1]
```diff
@@ -265,6 +265,54 @@ def position_considering_colspan(xpath)
...
+    def _run_in_disclosure(name, **find_options, &block)
+      attempts = 0
+      begin
+        attempts += 1
+        disclosure = if is_a?(Capybara::Node::Element) && name.nil?
+                       _locate_disclosure(name, **find_options)
+                     else
+                       Capybara.page.find(:disclosure, name, **find_options)
+                     end
+        block_executed = false
```
Comment (gianfrancopiana) [inline spec/support/aria_extensions.rb]: Two different `StaleElementReferenceError` scenarios here:
1. Radix re-renders the popover for positioning right after mount, invalidating the `within` scope before the block runs. We retry with a fresh reference.
2. `PopoverClose` unmounts content *after* the block's click already happened. Safe to swallow. The flag tells them apart.

File: app/javascript/components/TiptapExtensions/Link.tsx [hunk 2]
```diff
@@ -319,34 +295,42 @@ const TiptapButton = Node.create({
...
-export const LinkMenuItem = ({ editor }: { editor: Editor }) => (
-  <WithDialog editor={editor} type="link">
-    <MenuItem
-      name="Insert link"
-      icon={<LinkIcon className="size-5" />}
-      active={editor.isActive("link") || !!editor.getAttributes("image").link}
-    />
-  </WithDialog>
-);
+export const LinkMenuItem = ({ editor }: { editor: Editor }) => {
```
Comment (gianfrancopiana) [inline app/javascript/components/TiptapExtensions/Link.tsx:313]: `LinkMenuItem` manages its own dialog state because it lives in the toolbar (always mounted). Button and X post can't do this. They're rendered inside the insert menu popover, so `PopoverClose` would destroy their state before the modal opens. Those go through `openDialogForExtension` in `RichTextEditor` instead.

File: app/javascript/components/ProductEdit/ContentTab/index.tsx [hunk 3]
```diff
@@ -141,11 +141,10 @@ const FileUploadMenu = ({
       </div>
     </PopoverClose>
     <PopoverClose asChild>
-      <label role="menuitem">
-        <input type="file" name="file" className="sr-only" multiple onChange={(e) => onUploadFile(e.target)} />
+      <div role="menuitem" onClick={onClickComputerFiles}>
```
Comment (gianfrancopiana) [inline app/javascript/components/ProductEdit/ContentTab/index.tsx:146]: The file input was previously inside `PopoverClose`. After file selection, the popover closed and destroyed the input before `onChange` fired. Moved it to the component root (line 565) with a ref so it stays alive.

File: app/javascript/components/TiptapExtensions/MediaEmbed.tsx [hunk 4]
```diff
@@ -34,10 +32,9 @@ declare module "@tiptap/core" {
 const MEDIA_EMBED_SUPPORTING_PROVIDERS = ["YouTube", "Vimeo", "Wistia, Inc.", "Dailymotion"];
 
 const VideoEmbed = Extension.create({
-  menuItem: (editor) => (
-    <WithDialog editor={editor} type="embed">
-      <MenuItem name="Insert video" icon={<Video className="size-5" />} />
-    </WithDialog>
+  name: "videoEmbed",
```
Comment (gianfrancopiana) [inline app/javascript/components/TiptapExtensions/MediaEmbed.tsx:35]: Was unnamed before. Needed now so `openDialogForExtension` can map extension name → dialog opener.

File: app/javascript/components/Popover.tsx [hunk 5]
```diff
@@ -53,11 +53,8 @@ export const PopoverContent = React.forwardRef<
         ref={ref}
         align={align}
         collisionPadding={collisionPadding}
-        autoFocus={false}
-        forceMount
-        onOpenAutoFocus={(e: Event) => e.preventDefault()}
         className={classNames(
-          "z-30 w-max max-w-[calc(100vw-2rem)] rounded-sm border border-border bg-background p-4 text-foreground shadow outline-none focus-visible:outline-none data-[state=closed]:hidden",
```
Comment (gianfrancopiana) [inline app/javascript/components/Popover.tsx:60]: With `forceMount`, content stayed in DOM and needed CSS to hide. Without it, Radix unmounts naturally and the class is no longer needed.

**Comment by binary-koan** [comment]
Thanks for the reminder - there are still some related failing tests (e.g. missing "Search products" input in Slow 0) which I was planning to just quickly fix myself, but haven't found time. Will get to it after the Tailwind migration, or lmk if you can fix them earlier

**Comment by gianfrancopiana** [comment]
@binary-koan Can you please review?
