### PR TITLE
Fix: product thumbnail missing in upsell insert 

### LINKED ISSUE #3431: Product thumbnail missing in upsell insert
Upsell insert in a product's description shows the default Gumroad icon instead of the target product's thumbnail. 

Example: https://wibstore.gumroad.com/l/stock

Image

Target product thumbnails: 
Image

### PR DESCRIPTION
**Pull request by romitg2**
fixes #3431 

# Description

## Problem

  The `Checkout::Upsells::ProductPresenter` was not including `thumbnail_url` in the product data returned to the frontend. As a result, `UpsellCard.tsx`  always passed `url={null}` to the `Thumbnail` component, causing it to display the default icon instead of the actual product thumbnail.

## Solution

  - Added `thumbnail_url: product.thumbnail_or_cover_url` to the presenter
  - Updated `UpsellCard.tsx` to use the thumbnail URL from the API response
  - Added test coverage for products with thumbnails

---

# Before/After

## Before: 
Screenshot 2026-02-09 at 10 38 24 AM

## after: 
Screenshot 2026-02-09 at 10 36 43 AM

https://github.com/user-attachments/assets/d3c63e8a-5e06-4fc7-abd8-afa0115598f3

---

# Test Results

presenter specs: 
Screenshot 2026-02-09 at 10 40 37 AM

controller specs: 
Screenshot 2026-02-09 at 10 59 36 AM

# Checklist

- [x] I have read the [contributing guidelines](https://github.com/antiwork/gumroad/blob/main/CONTRIBUTING.md)
- [x] I have watched [Gumroad PR review livestreams](https://www.youtube.com/@anti-work)
- [x] I have performed a self-review and left review comments on my PR
- [x] I have added/updated tests for my changes

---

# AI Disclosure

used claude-code opus 4.5 to find root cause

### CODE REVIEW

File: app/presenters/checkout/upsells/product_presenter.rb [hunk 1]
```diff
@@ -15,6 +15,7 @@ def product_props
       review_count: product.reviews_count,
       average_rating: product.average_rating,
       native_type: product.native_type,
+      thumbnail_url: product.thumbnail_or_cover_url,
```
Comment (romitg2) [inline app/presenters/checkout/upsells/product_presenter.rb:18]: The `Checkout::Upsells::ProductPresenter` was not including `thumbnail_url` in the product data returned to the frontend. As a result, `UpsellCard.tsx`  always passed `url={null}` to the `Thumbnail` component, causing it to display the default icon instead of the actual product thumbnail.
