### PR TITLE
Fix: Suspend For Fraud/Mark Compliant Creates Duplicate Comments On Related Accounts

### LINKED ISSUE #2833: Bug: Suspend For Fraud/Mark Compliant Creates Duplicate Comments On Related Accounts
## What
1. Suspending a user for fraud creates duplicate suspension comments on related creator accounts (Accounts with same PayPal payout address)
2. Marking a user account as compliant creates duplicate comments on related creator accounts

## Expected behaviour 
Only one comment (from the original user) per risk state transition should be applied while performing any of the above actions

> [!NOTE]
> This bug doesn't break anything per se,  just cleaning it up since it got noticed

### Case 1 - While Suspending a Creator Account
Spec - `bundle exec rspec spec/models/user_spec.rb:1873`

For this spec, I've added another user with same payout address and enabled `sidekiq_inline` for suspension worker to run. Related accounts should have two comments each, one for fraud and one for suspension, but that isn't the case for some.

Image

### Case 2 - 
Spec - `bundle exec rspec spec/models/user_spec.rb:1891`

For this spec, I've added another user with same payout address. Related accounts should have one compliant comment each, but that isn't the case for some.

Image

### PR DESCRIPTION
**Pull request by sm17p**
Closes #2833

## Root Cause

For both the cases risk state transition callbacks namely `suspend_sellers_other_accounts` and `enable_sellers_other_accounts` were being called recursively, creating a race condition that resulted in duplicate comments on related creator accounts.

### Case 1 - Suspending a user for fraud (User A, B & C with same PayPal Payment address)
- `User A` is suspended and `suspend_sellers_other_accounts` callback triggers
- `SuspendAccountsWithPaymentAddressWorker` suspends related accounts `User B` and `User C`
- When User B (related account) is suspended, their `suspend_sellers_other_accounts` callback triggers again, which creates duplicate suspension comments on `User C`

### Case 2 - Marking a user account as compliant (User A, B & C with same PayPal Payment address)
- `User A` is marked compliant and `enable_sellers_other_accounts` callback triggers
- Related accounts `User B` and `User C` are marked compliant directly
- When `User B` (related account) transitions to compliant, their `enable_sellers_other_accounts` callback triggers again, which creates duplicate compliance comments on `User C` 

## Solution
The fix uses the `skip_transition` parameter to prevent recursive callback execution

- `SuspendAccountsWithPaymentAddressWorker` now passes `skip_transition_callback: :suspend_sellers_other_accounts` when suspending related accounts 
- `enable_sellers_other_accounts` passes `skip_transition_callback: :enable_sellers_other_accounts` when marking related accounts compliant
- Both callbacks check for this parameter and return early if present, breaking the recursion.

### Case 1 - Suspending a user for fraud
Passes with one fraud and one suspension comment from originating user for each related account

after-no-duplicate-suspension-comments

### Case 2 - Marking a user account as compliant 
Passes with one compliant comment from originating user for each related account

after-no-duplicate-compliant-comments

# Checklist

- [x] I have read the [contributing guidelines](https://github.com/antiwork/gumroad/blob/main/CONTRIBUTING.md)
- [x] I have watched [Gumroad PR review livestreams](https://www.youtube.com/@anti-work)
- [x] I have performed a self-review and left review comments on my PR
- [x] I have added/updated tests for my changes

---

# AI Disclosure

I've used Cursor Auto mode to edit specs and referencing docs for rspec, sidekiq

### CODE REVIEW

File: app/sidekiq/suspend_accounts_with_payment_address_worker.rb [hunk 1]
```diff
@@ -9,14 +9,15 @@ def perform(user_id)
 
     return if suspended_user.payment_address.blank?
 
-    User.where(payment_address: suspended_user.payment_address).where.not(id: suspended_user.id).find_each do |user|
+    User.where(payment_address: suspended_user.payment_address).where.not(id: suspended_user.id).not_suspended.find_each do |user|
```
Comment (sm17p) [inline app/sidekiq/suspend_accounts_with_payment_address_worker.rb:12]: Just adding the `not_suspended` scope over here to account for job failures/re-start

File: spec/models/user_spec.rb [hunk 2]
```diff
@@ -1870,10 +1870,16 @@ def sample_string_of_length(n)
...
 
-      it "suspends all the others sellers accounts if suspended for fraud" do
-        expect(@user).to receive(:suspend_sellers_other_accounts)
+      it "suspends all the others sellers accounts if suspended for fraud", :sidekiq_inline do
+        user_3 = create(:user, payment_address: "sameuser@gmail.com")
+        expect(@user).to receive(:suspend_sellers_other_accounts).and_call_original
         @user.flag_for_fraud(author_id: @admin_user.id)
         @user.suspend_for_fraud(author_id: @admin_user.id)
+        expect(user_3.reload.suspended?).to be(true)
+        expect(@user_2.reload.suspended?).to be(true)
```
Comment (sm17p) [inline spec/models/user_spec.rb:1879]: Asserting over suspended state over here for completeness

File: spec/models/user_spec.rb [hunk 3]
```diff
@@ -1870,10 +1870,16 @@ def sample_string_of_length(n)
         expect(@product_1.reload.banned_at).to be(nil)
       end
 
-      it "suspends all the others sellers accounts if suspended for fraud" do
-        expect(@user).to receive(:suspend_sellers_other_accounts)
+      it "suspends all the others sellers accounts if suspended for fraud", :sidekiq_inline do
```
Comment (sm17p) [inline spec/models/user_spec.rb:1873]: Added `sidekiq_inline` to ensure the suspension worker is executed during this test

File: spec/models/user_spec.rb [hunk 4]
```diff
@@ -1883,14 +1889,22 @@ def sample_string_of_length(n)
...
         @user.flag_for_fraud(author_id: @admin_user.id)
         @user.suspend_for_fraud(author_id: @admin_user.id)
         expect(@user_2.reload.suspended?).to be(true)
+        expect(@user_2.comments.count).to eq(2)
+        expect(user_3.reload.suspended?).to be(true)
 
         @user.mark_compliant(author_id: @admin_user.id)
-        expect(@user_2.reload.suspended?).to be(false)
+        expect(user_3.reload.compliant?).to be(true)
+        expect(@user_2.reload.compliant?).to be(true)
```
Comment (sm17p) [inline spec/models/user_spec.rb:1904]: Asserting over compliant state over here for completeness

File: spec/modules/user/risk_spec.rb [hunk 5]
```diff
@@ -42,4 +42,24 @@
...
+          user.suspend_sellers_other_accounts(transition)
+        }.to change(SuspendAccountsWithPaymentAddressWorker.jobs, :size).from(0).to(1)
+        .and change { SuspendAccountsWithPaymentAddressWorker.jobs.last&.dig('args') }.to([user.id])
+
+        expect {
+          SuspendAccountsWithPaymentAddressWorker.perform_one
+        }.to change(SuspendAccountsWithPaymentAddressWorker.jobs, :size).from(1).to(0)
+      end
+    end
+  end
```
Comment (sm17p) [inline spec/modules/user/risk_spec.rb:64]: Added this unit test to prepare for #2829.

My plan is to unit test `suspend_sellers_other_accounts` for stripe accounts in #2829 over here as well, so that I can just write a light weight integration spec in `user_spec.rb`. 

LMK if this sounds like a good plan

File: spec/modules/user/risk_spec.rb [hunk 6]
```diff
@@ -42,4 +42,24 @@
...
+        create(:user, payment_address: "test@example.com")
+
+        expect {
+          user.suspend_sellers_other_accounts(transition)
+        }.to change(SuspendAccountsWithPaymentAddressWorker.jobs, :size).from(0).to(1)
+        .and change { SuspendAccountsWithPaymentAddressWorker.jobs.last&.dig('args') }.to([user.id])
+
+        expect {
+          SuspendAccountsWithPaymentAddressWorker.perform_one
+        }.to change(SuspendAccountsWithPaymentAddressWorker.jobs, :size).from(1).to(0)
```
Comment (sm17p) [inline spec/modules/user/risk_spec.rb]: This verifies `skip` path was taken for `suspend_sellers_other_accounts`

**Review by sm17p — COMMENTED** [review]
Please have a look this is ready for review 🙏

**Review by nyomanjyotisa — APPROVED** [review]
Looks good to me. Thanks for the PR!

## Before/after
3 accounts with same PayPal payment address. Action: Suspend account A for fraud -> mark compliant account A
### Before (total 7 actions/comments on account B)
image


### After (correctly 3 actions/comments on account B)
Screenshot 2026-01-20 at 13 42 20
